### PR TITLE
Make packages reproducible

### PR DESCRIPTION
**Pull request by rustybird**

### CODE REVIEW

**Comment by rustybird** [comment]
An interesting alternative to this PR might be to have qubes-builder itself (independent from the individual builder plugins) set `SOURCE_DATE_EPOCH` as part of `CHROOT_ENV`. [**Edit:** `Makefile-mock.rpmbuilder` and `Makefile-pbuilder.debian` currently ignore `CHROOT_ENV`, so they'd have to be adjusted too.] This would take care of RPMs without a changelog, and make it slightly easier to write new builder plugins.

(For RPMs _with_ a changelog, the environment variable would also take precedence over `%source_date_epoch_from_changelog`, so the define could be removed - neither a pro nor a con I guess, but different.)

**Comment by marmarek** [comment]
> This would take care of RPMs

Not really - mock (and I believe pbuilder too) by design isolate the build from outside environment.
Also, we try to be as much compatible with upstream tools as possible. If we take a different timestamp (git commit instead of changelog entry) as SOURCE_DATE_EPOCH than native build, rebuilding debian/fedora source package will result in a different binary. With the current approach, it should be possible to fetch src.rpm from repository, rebuild it with mock (possibly adding those defines, but AFAIR they should be enabled by default starting with some version) and get exactly the same binary - without relying on qubes-builder.

BTW is there a tool for arch packages that also takes care about build environment setup (similar to mock/pbuilder/sbuild/...)? If there is, I would a) check how it sets SOURCE_DATE_EPOCH (if at all) and b) consider using it here instead of manual chroot construction (if feasible).
cc @ptitdoc

**Comment by rustybird** [comment]
I meant it would take care of those RPMs whose specs are missing a changelog (or whose `%changelog` section is empty). [**Edit:** Oh I see, even for those there's still the problem with rebuilding outside of qubes-builder.] Not sure how many there are, maybe even none at all under QubesOS/?

> If we take a different timestamp (git commit instead of changelog entry) as SOURCE_DATE_EPOCH than native build, rebuilding debian/fedora source package will result in a different binary.

Ah, right. Ok that sucks.

> BTW is there a tool for arch packages that also takes care about build environment setup (similar to mock/pbuilder/sbuild/...)? If there is, I would a) check how it sets SOURCE_DATE_EPOCH (if at all) and b) consider using it here instead of manual chroot construction (if feasible).

No idea... Feel free to close this PR if it's not a good approach.

**Comment by rustybird** [comment]
Would it make sense to merge this anyway for QubesOS/qubes-issues#5929? Seems better than nothing, and it would be easy to replace with another mechanism if one is found.

**Comment by marmarek** [comment]
Yes, I agree. And later we can adjust to an upstream approach if someone can figure out what it is.

**Pull request merged**
