### PR TITLE
disable qubes package repository so that users have to enable it

### PR DESCRIPTION
**Pull request by ptitdoc**
Following discussion on https://github.com/QubesOS/qubes-builder-archlinux/pull/16

### CODE REVIEW

**Comment by ptitdoc** [comment]
Apparently I need each time to push the signed tag before the branch, or github doesn't analyse my signatures.

**Comment by ptitdoc** [comment]
Based on this code, I can now build a working template.

I still have to update the documentation.

**Comment by marmarek** [comment]
> Apparently I need each time to push the signed tag before the branch, or github doesn't analyse my signatures.

You can push both at the same time using `--tags` option for `git push`.

**Comment by marmarek** [comment]
Or, you can enable commits signing instead of tags (or in addition to if you like).

**Pull request merged**
