### PR TITLE
Retry pacman a maximum of 5 times

### PR DESCRIPTION
**Pull request by DemiMarie**
Retrying forever is a very bad idea, as pointed out in
QubesOS/qubes-issues#7048.  Instead of duplicating the retry logic
several different places, use a common function for it.

### CODE REVIEW

**Comment by ejose19** [comment]
Just tried this patch, however there's an issue somewhere because if I try to `ctrl-c` when pacman is installing packages it will retry 5 times to exit instead of exiting the first time, maybe we can add a `SIGINT`/`SIGTERM` handler?

**Comment by DemiMarie** [comment]
> Just tried this patch, however there's an issue somewhere because if I try to `ctrl-c` when pacman is installing packages it will retry 5 times to exit instead of exiting the first time, maybe we can add a `SIGINT`/`SIGTERM` handler?

That would be a good idea.  Separate PR?

**Comment by ejose19** [comment]
> > Just tried this patch, however there's an issue somewhere because if I try to `ctrl-c` when pacman is installing packages it will retry 5 times to exit instead of exiting the first time, maybe we can add a `SIGINT`/`SIGTERM` handler?
> 
> That would be a good idea. Separate PR?

[Done](https://github.com/QubesOS/qubes-builder-archlinux/pull/58)

**Comment by DemiMarie** [comment]
> > > Just tried this patch, however there's an issue somewhere because if I try to `ctrl-c` when pacman is installing packages it will retry 5 times to exit instead of exiting the first time, maybe we can add a `SIGINT`/`SIGTERM` handler?
> > 
> > 
> > That would be a good idea. Separate PR?
> 
> [Done](https://github.com/QubesOS/qubes-builder-archlinux/pull/58)

Thanks!

**Review by marmarek — APPROVED** [review]

**Pull request merged**
