### PR TITLE
Set human readable pacman output : no progress bar in scripts

### LINKED ISSUE #9172: infrastructure: ArchLinux continuous integration and delivery produces difficult to read logs
### The problem you're addressing (if any)
The ArchLinux ci/cd logs contains a lot of unreadable output.
Example1:
```
08:35:47,772 executor:docker:b166b4047936] output: :: Retrieving packages....
08:35:47,772 executor:docker:b166b4047936] output:  ghc-libs-9.2.8-1-x86_64.
08:35:47,773 executor:docker:b166b4047936] output:  Total (  0/293)         0.0   B  0.00   B/s 00:00 [----------------------]   0%..
...
08:35:49,144 executor:docker:b166b4047936] output: ghc-libs-9.2.8-1...     7.7 KiB  19.0   B/s --:-- [----------------------]   0%. Total (  0/293)         7.7 KiB  19.0   B/s --:-- [----------------------]   0%. python-numpy-1.2...     7.7 KiB  19.0   B/s --:-- [----------------------]   0%. python-3.12.3-1-...     7.7 KiB  19.0   B/s --:-- [----------------------]   0%. haskell-pandoc-3...     7.7 KiB  19.0   B/s --:-- [----------------------]   0%. haskell-texmath-...     7.7 KiB  19.0   B/s --:-- [----------------------]   0%..[4F ghc-libs-9.2.8-1...    85.9 KiB   125 KiB/s 02:11 [----------------------]   0%..[5E Total (  0/293)       398.0 KiB   622 KiB/s 02:53 [----------------------]   0%. python-3.12.3-1-...    85.9 KiB   128 KiB/s 01:39 [----------------------]   0%. haskell-pandoc-3...    78.0 KiB   115 KiB/s 01:09 [----------------------]   0%..[1E python-numpy-1.2...    62.4 KiB  88.9 KiB/s 01:14 [----------------------]   0%..[1E haskell-texmath-...    85.9 KiB   128 KiB/s 00:29 [----------------------]   2%..[4F ghc-libs-9.2.8-1...   406.2 KiB   615 KiB/s 00:26 [----------------------]   2%..[5E Total (  0/293)      1905.8 KiB  2.86 MiB/s 00:36 [----------------------]   1%..[4F python-3.12.3-1-...   374.9 KiB   567 KiB/s 00:21 [----------------------]   2%..[1E haskell-pandoc-3...   398.4 KiB   610 KiB/s 00:12 [----------------------]   4%..[1E python-numpy-1.2...   320.2 KiB   489 KiB/s 00:12 [----------------------]   4%..[1E haskell-texmath-...   406.2 KiB   619 KiB/s 00:05 [##--------------------]  10%..[4F ghc-libs-9.2.8-1...     3.2 MiB  5.13 MiB/s 00:02 [####------------------]  20%..[5E Total (  0/293)        11.2 MiB  17.5 MiB/s 00:05 [##--------------------]  10%..[4F python-3.12.3-1-...  1703.0 KiB  2.53 MiB/s 00:04 [##--------------------]  13%..[1E haskell-pandoc-3...     2.3 MiB  3.60 MiB/s 00:01 [######----------------]  29%..[1E python-numpy-1.2...     2.4 MiB  3.80 MiB/s 00:01 [#######---------------]  36%..[1E haskell-texmath-...  1687.4 KiB  2.49 MiB/s 00:00 [#########-------------]  44%..[4F ghc-libs-9.2.8-1...     8.9 MiB  12.8 MiB/s 00:00 [###########-----------]  54%..[5E Total (  0/293)        26.9 MiB  37.8 MiB/s 00:02 [#####-----------------]  25%..[4F python-3.12.3-1-...     4.6 MiB  6.65 MiB/s 00:01 [########--------------]  37%..[1E haskell-pandoc-3...     5.5 MiB  7.67 MiB/s 00:00 [###############-------]  69%..[1E python-numpy-1.2...     4.9 MiB  6.76 MiB/s 00:00 [################------]  75%..[1E haskell-texmath-...     3.0 MiB  3.92 MiB/s 00:00 [#################-----]  80%..[1F ghc-libs-9.2.8-1...     8.9 MiB  12.8 MiB/s 00:00 [###########-----------]  54%..[3F python-numpy-1.2...     6.5 MiB  5.77 MiB/s 00:01 [######################] 100%..[2E python-3.12.3-1-...     4.6 MiB  6.65 MiB/s 00:01 [########--------------]  37%..[1F haskell-pandoc-3...     7.9 MiB  6.98 MiB/s 00:01 [######################] 100%..[3E python-3.12.3-1-...     4.6 MiB  6.65 MiB/s 00:01 [########--------------]  37%..[2F haskell-texmath-...     3.7 MiB  3.12 MiB/s 00:01 [######################] 100%..[1E ghc-libs-9.2.8-1...    16.2 MiB  12.7 MiB/s 00:01 [######################] 100%..[1E python-3.12.3-1-...    10.5 MiB  14.1 MiB/s 00:00 [##################----]  84%..[1E Total (  4/293)        44.8 MiB  54.4 MiB/s 00:01 [#########-------------]  42%..[1F python-3.12.3-1-...    12.5 MiB  9.23 MiB/s 00:01 [######################] 100%..[1E lapack-3.12.0-5-x86_64.
```
Example2 [jobs#6733491339](https://gitlab.com/QubesOS/qubes-core-agent-linux/-/jobs/6733491339):
```
08:36:46,806 [executor:docker:b166b4047936] output: (  0/293) checking package integrity               [----------------------]   0%.(  1/293) checking package integrity               [----------------------]   0%.(  2/293) checking package integrity               [----------------------]   0%.(  3/293) checking package integrity               [----------------------]   0%.(  4/293) checking package integrity               [----------------------]   0%.(  5/293) checking package integrity               [----------------------]   1%.(  6/293) checking package integrity               [----------------------]   3%.(  7/293) checking package integrity               [----------------------]   3%.(  8/293) checking package integrity               [###-------------------]  15%.(  9/293) checking package integrity               
```

### The solution you'd like
The pacman logs contain a lot of downloading progress bars. Luckily, the pacman command provides the ` --noprogressbar` option (see [man 8 pacman](https://archlinux.org/pacman/pacman.8.html))

### The value to a user, and who that user might be
More readable logs so easier to find the errors.

### Completion criteria checklist

(This section is for developer use only. Please do not modify it.)

### PR DESCRIPTION
**Pull request by lubellier**
Add `--noprogressbar` to pacman to avoid unreadable progressbar in the logs.
Fixes : QubesOS/qubes-issues/issues/9172

### CODE REVIEW

**Comment by lubellier** [comment]
1) The _r4.2:build:archlinux_  pipeline stage failed with:
```
13:34:54,018 [executor:docker:2c44e8a0fac1] output: Enter a number (default=1): warning: cannot resolve "python<3.12", a dependency of "qubes-vm-core"
13:34:54,018 [executor:docker:2c44e8a0fac1] output: warning: cannot resolve "qubes-vm-core", a dependency of "qubes-vm-dependencies"
```
So should wait QubesOS/qubes-issues/issues/9171 before retry the pipeline.

2) The _build:vm-archlinux_ pipeline stage failed with:
```
==> ERROR: replaces does not allow empty values.
Container chroot-vm-archlinux failed with error code 12.
```
but I didn't understand the origin of this failure...

**Comment by marmarek** [comment]
PipelineRetryFailed

**Comment by lubellier** [comment]
Now it's OK for the `r4.2:build:archlinux` job.  :+1: 

The `build:vm-archlinux`job failed line [L397](https://gitlab.com/QubesOS/qubes-builder-archlinux/-/jobs/6758360766#L396) with:
```
Press Ctrl-] three times within 1s to kill container.
==> ERROR: replaces does not allow empty values.
Container chroot-vm-archlinux failed with error code 12.
```
What is the empty value for which replacement ? Is-it a bad argument in the above `systemd-nspawn` command?

**Comment by marmarek** [comment]
No, it is https://github.com/QubesOS/qubes-core-qrexec/commit/40a01734229dc5242cf8c600ecb3c9e100996175

**Comment by lubellier** [comment]
The qubes-core-qrexec [pipeline](https://gitlab.com/QubesOS/qubes-core-qrexec/-/jobs/6759970218) for the (r4.1) 4.1.25 release failed with 3 times  `_FORTIFY_SOURCE` defined. See [L982](https://gitlab.com/QubesOS/qubes-core-qrexec/-/jobs/6759970218#L982) in `gcc unix-server.c -c -o unix-server.o`. 1x `-D_FORTIFY_SOURCE=2`, 2x `-D_FORTIFY_SOURCE=3`.
The error message is `<command-line>: error: "_FORTIFY_SOURCE" redefined [-Werror]`.

**Comment by marmarek** [comment]
Uhg, here too...

**Comment by marmarek** [comment]
PipelineRetry

**Comment by lubellier** [comment]
All the jobs are green, thanks a lot for all your fixes.

**Review by marmarek — APPROVED** [review]

**Pull request merged**
