### PR TITLE
Update build scripts to use sha256sums file when searching for tarball

### LINKED ISSUE #7874: Archlinux Template: Build failes in early stage (00_prepare.sh)
### Qubes OS release

4.1.1

### Brief summary

Archlinux image does not build correctly. It fails silently (even with VERBOSE or DEBUG env vars set).
Apparently since October 2022, `sha1sum` file is no longer present on the mirrors. There is a `sha256sum` still available.
Unfortunately I have not found it mentioned in Arch Linux release notes.

### Steps to reproduce

Try building archlinux template.

### Expected behavior

Build end successfully.

### Actual behavior

Build fails.

### PR DESCRIPTION
**Pull request by tezeb**
Fix https://github.com/QubesOS/qubes-issues/issues/7874

### CODE REVIEW

**Comment by marmarek** [comment]
PipelineRefresh

**Comment by tezeb** [comment]
PipelineRefresh

**Comment by tezeb** [comment]
This CI is really fragile o_O.

**Comment by tezeb** [comment]
This should fix https://github.com/QubesOS/qubes-issues/issues/7875 as well.

**Comment by tezeb** [comment]
The previous CI build result, which failed probably on `wget` or `grep`:
https://gitlab.com/QubesOS/qubes-builder-archlinux/-/jobs/3315232928
The commands executes correctly and returns expected results when runned locally.
Funnily enough, there was a single successful build here, but I left my debug comment in there :/.
https://gitlab.com/QubesOS/qubes-builder-archlinux/-/pipelines/693025125

**Comment by tezeb** [comment]
With the verbose output from `wget`:
https://gitlab.com/QubesOS/qubes-builder-archlinux/-/pipelines/693327730
it is visible that it breaks on DNS resolution, which works fine from other computers. Is it a configuration limitation or just
some random network issues? I am happy to provide a fix, but I will need some guidance on how this is expected to work?
Should we use a list of mirrors and go on them one by one until successful? Or maybe just changing a mirror to another one is the way to go?

**Pull request merged**
