### PR TITLE
fix generating local package repositories using last package versions

### PR DESCRIPTION
**Pull request by ptitdoc**

### CODE REVIEW

**Comment by marmarek** [comment]
Does it fix missing `Include = /etc/pacman.d/*.conf`?

**Comment by marmarek** [comment]
I guess it's unrelated.

**Comment by ptitdoc** [comment]
In my case it caused to install old packages in my template instead of the one I just built, so I could be related.
However I need to access to a system with Qubes version 3.2 to analyse the template you built last time. (I'm currently working with a 3.1 system).

**Comment by ptitdoc** [comment]
At least the template now build successfully.

**Comment by ptitdoc** [comment]
I finally identified the bug for `Include = /etc/pacman.d/*.conf` in the core-agent-linux component.

However, I still need to disable my binary repository in the created templates, which requires knowing QUBES_RELEASE inside 04_install_qubes.sh.

Do you have any idea how to get this variable ?

**Comment by marmarek** [comment]
Template builder itself by design don't know this value (at least not explicitly). What about looking what repositories are installed in /etc/pacman.d? Or checking qubes-vm-core package version?

**Comment by ptitdoc** [comment]
Well, I think I will choose the first solution. Thanks for your help anyway, you saved my digging through all variables for nothing.

**Pull request merged**
