### PR TITLE
fix generating local package repositories using last package versions

### PR DESCRIPTION
**Pull request by ptitdoc**

### CODE REVIEW

**Comment by marmarek** [comment]
@ptitdoc could you sign your code (either signed tags or commits)? See here: https://www.qubes-os.org/doc/code-signing/

**Comment by ptitdoc** [comment]
I will add a signed tag.

**Comment by ptitdoc** [comment]
Replaced by signed tag instead of master

**Comment by ptitdoc** [comment]
Sorry, I signed a tag, b

**Pull request closed without merging**
